### PR TITLE
Problem: Fee middleware is not enabled for ICA module

### PR DESCRIPTION
**Pull request by devashishdxt**
Solution: Enable fee middleware for ICA module

### CODE REVIEW

**Review by tomtau — APPROVED** [review]
does it work now? there's a fail on the ibc integration test: https://github.com/crypto-org-chain/chain-main/runs/7798690698?check_suite_focus=true

**Comment by devashishdxt** [comment]
> does it work now? there's a fail on the ibc integration test: https://github.com/crypto-org-chain/chain-main/runs/7798690698?check_suite_focus=true

Fixed app wiring. It should work now.

**Pull request merged**
