### PR TITLE
Problem: Crypto.org Chain is renamed to Cronos POS Chain

### PR DESCRIPTION
**Pull request by calvinaco**
Solution: Rename all occurrences to updated values

👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest master? 
- [ ] Have you checked your code compiles? (`make`)
- [ ] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`make test`)
- [ ] Have you checked your code formatting is correct? (`go fmt`)
- [ ] Have you checked your basic code style is fine? (`golangci-lint run`)
- [ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`go list -json -m all | nancy sleuth`)
- [ ] If your changes affect the client infrastructure, have you run the integration test?
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-org-chain/chain-main/blob/master/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md#developer-certificate-of-originn).

Thank you for your code, it's appreciated! :)

### CODE REVIEW

**Comment by thomas-nguy** [comment]
is it still a draft ? @calvinaco

**Comment by infinitebreakfast** [comment]
I just want to know how I ever sent usdc via the cronos network and not erc 20. I will never understand how so much good work goes into this network when the app is still written in crayon.

**Comment by yihuang** [comment]
> I just want to know how I ever sent usdc via the cronos network and not erc 20. I will never understand how so much good work goes into this network when the app is still written in crayon.

hi, how can we help you? which application do you mean?

**Comment by infinitebreakfast** [comment]
Salutations and hello. Back in 2022, many changes to the cdc.app as a result of either hacking or change in policy caused an error in a transaction that absolutely SHOULD have never happened. I had transacted in various crypto. Mostly xlm, but never making the mistake of sending coins via the wrong network. I digress, as i stated I had previously transacted in USDC and on this particular day, after an update to the platform. ERC-20 was no longer the DEFAULT setting for sending USDC. Instead CRONOS network was the default setting. I sent a transfer of 500 usdc via cronos. It still sits here to this day and im positive that it can be recovered before waiting for CRO to be offered at kraken exchange. 

Below is the adresss. 

If nothing else. Explain to me how 5 other tokens have managed to find their way to this address on the cronos network. I understand the concept of TVL. But this was a very expensive lesson that could have been avoided. I have been waiting for a response from CDC for issues as benign as referral bonuses for over 2 weeks. There has never been an intelligent explanation furnished from CDC as to why this happened. Makes me laugh, given that story where by they sent 25 million dollars in eth to the wrong address. Yet somehow they were able to reverse this transaction. 

I understand the concept (to a degree) of custodial wallets. Kraken at this time does not offer a custodial wallet, still has always rubbed me the wrong way that it was not soley user error. There never should have even been the option to send an ERC -20 token via CRONOs. Like i stated i had transacted not only in USDC but several other currencies and never had an issue until several changes at the time on CDC platform with respect to UI layout, and Whitelisted addresses.

Thank you for coming to my ted talk. 

If nothing else i hope to understand how the additional tokens came to find themselves parked in the same location as my 500.20 usdc. 

0xaF54ce06bc1384158b016B2E33cc3A452D1862fd

**Comment by infinitebreakfast** [comment]
B08F0F8A-945E-46DE-ACD3-E1A55E077B84
6C9DCF43-62A2-46A3-A8F7-919BCB01237E


I have proof. Of the changes they made to the ui.

**Comment by infinitebreakfast** [comment]
> > I just want to know how I ever sent usdc via the cronos network and not erc 20. I will never understand how so much good work goes into this network when the app is still written in crayon.
> 
> hi, how can we help you? which application do you mean?

Crypto.com app crypto.com defi. Takes 1 min or less to receive xlm more than 45 to send. I would definitely love to understand what the cronos network adds to utility. Should try the exchange just to short in volatility but lol kraken pro exists. Coinbase pro exist. The only way this company moves up in the food chain is by way of other companies disappearing entirely. Idk how cdc or cro ever gets compared to bnb. Market cap and volume are real things!

**Review by Boyka0805 — APPROVED** [review]
[proof-of-reserves-master.zip](https://github.com/user-attachments/files/16353163/proof-of-reserves-master.zip)

**Review by Boyka0805 — APPROVED** [review]
[proof-of-reserves-master.zip](https://github.com/user-attachments/files/16353163/proof-of-reserves-master.zip)

**Review by Boyka0805 — APPROVED** [review]
[proof-of-reserves-master.zip](https://github.com/user-attachments/files/16353163/proof-of-reserves-master.zip)

**Comment by yihuang** [comment]
fixed by: https://github.com/crypto-org-chain/chain-main/pull/1071

**Pull request closed without merging**
