### PR TITLE
Problem: `cosmos-sdk` and `ibc-go` version not upgraded to latest

### LINKED ISSUE #708: Problem: `cosmos-sdk` and `ibc-go` version not upgraded to latest
Latest released Cosmos SDK version: `0.45.1`
Latest released IBC version: `3.0.0-rc0`

Checklist:

- [ ] Upgrade `cosmos-sdk` to `v0.45.1`
- [ ] Upgrade `ibc-go` to `v3.0.0-rc0`
- [ ] Make necessary code changes and fix integration tests
- [ ] Update `gomod2nix.toml`
- [ ] Update `cosmos-sdk` git submodule
- [ ] Add upgrade handler
- [ ] Add upgrade test
- [ ] Add changelog

### PR DESCRIPTION
**Pull request by devashishdxt**
Solution: Upgraded `cosmos-sdk` and `ibc-go` versions. Fixes #708.

### CODE REVIEW

**Review by tomtau — COMMENTED** [review]
also will need an upgrade handler, given both are breaking?

**Comment by devashishdxt** [comment]
> also will need an upgrade handler, given both are breaking?

- No state migrations are required for upgrading Cosmos SDK from `v0.44.*` to `v0.45`
- No state migrations are required for IBC if we're not enabling inter-chain accounts (which I'll do in a future PR).

Do we still have to add an upgrade handler if there are no migrations to run?

**Comment by yihuang** [comment]
> Do we still have to add an upgrade handler if there are no migrations to run?

yes, we still need to register a plan name with an upgrade handler.

**Comment by devashishdxt** [comment]
The test failures are because of `out of gas` errors. @yihuang Is there any way to specify `gas_limit` without modifying `pystarport`?

**Comment by tomtau** [comment]
> Is there any way to specify gas_limit without modifying pystarport?
I remember @linfeng-crypto or @macong-cdc mentioned something about the gas limit in integration tests before

**Comment by devashishdxt** [comment]
Closing this for now. Will create a new PR.

**Pull request closed without merging**
