### PR TITLE
Problem: `cosmos-sdk` and `ibc-go` are not upgraded to latest versions

### PR DESCRIPTION
**Pull request by devashishdxt**
Solution: Upgraded `cosmos-sdk` to `v0.45.6` and `ibc-go` to `v4.0.0-rc0`. Fixes https://github.com/crypto-org-chain/chain-main/issues/801. Fixes https://github.com/crypto-org-chain/chain-main/issues/802.

Note: There is an indirect dependency of `ibc-go/v3` because we're using `wasmd` and later replacing with our own fork.

```
$ go mod why -m github.com/cosmos/ibc-go/v3

github.com/crypto-org-chain/chain-main/v4/app
github.com/CosmWasm/wasmd/x/wasm/keeper
github.com/CosmWasm/wasmd/x/wasm/keeper.test
github.com/CosmWasm/wasmd/app
github.com/cosmos/interchain-accounts/x/inter-tx/keeper
github.com/cosmos/ibc-go/v3/modules/apps/27-interchain-accounts/controller/keeper
```

### CODE REVIEW

**Review by tomtau — COMMENTED** [review]
it seems the integration tests are broken -- e.g. CLI args for staking changed `--moniker` to `--new-moniker`?

**Comment by devashishdxt** [comment]
> it seems the integration tests are broken -- e.g. CLI args for staking changed `--moniker` to `--new-moniker`?

Created a PR in `pystarport`: https://github.com/crypto-com/pystarport/pull/61

**Review by tomtau — APPROVED** [review]
should Nixpkgs be upgraded as well: https://github.com/crypto-org-chain/cronos/pull/573#issuecomment-1175949192 ?

**Comment by devashishdxt** [comment]
> should Nixpkgs be upgraded as well: [crypto-org-chain/cronos#573 (comment)](https://github.com/crypto-org-chain/cronos/pull/573#issuecomment-1175949192) ?

Created an issue for this: https://github.com/crypto-org-chain/chain-main/issues/804

**Pull request merged**
