### PR TITLE
Problem: chain-main doesn't use the upstream Cosmos SDK release

### PR DESCRIPTION
**Pull request by tomtau**
Solution: updated the dependencies to use 0.42.0 instead of the patched 0.41.4

### CODE REVIEW

**Review by devashishdxt — APPROVED** [review]

**Comment by JayT106** [comment]
Question for the Cosmos SDK submodule setup. Initially, I thought the reason we put this submodule because the Crypto.com  Cosmos SDK repo has its custom modification and might keeping update the codes. If we are using the Cosmos SDK official release. Is the submodule still necessary?

**Comment by devashishdxt** [comment]
> Question for the Cosmos SDK submodule setup. Initially, I thought the reason we put this submodule because the Crypto.com Cosmos SDK repo has its custom modification and might keep updating the code. If we are using the Cosmos SDK official release. Is the submodule still necessary?

Which submodule are you talking about?

**Comment by JayT106** [comment]
> > Question for the Cosmos SDK submodule setup. Initially, I thought the reason we put this submodule because the Crypto.com Cosmos SDK repo has its custom modification and might keep updating the code. If we are using the Cosmos SDK official release. Is the submodule still necessary?
> 
> Which submodule are you talking about?

the submodule "cosmos-sdk"

**Comment by devashishdxt** [comment]
> the submodule "cosmos-sdk"

Ah. You mean git submodule?

**Comment by JayT106** [comment]
> > the submodule "cosmos-sdk"
> 
> Ah. You mean git submodule?

Yes. However, just checked the project structure. Looks like `Nix` and `gPRC` need the submodule.

**Review by JayT106 — APPROVED** [review]
LGTM

**Comment by tomtau** [comment]
> Question for the Cosmos SDK submodule setup. Initially, I thought the reason we put this submodule because the Crypto.com Cosmos SDK repo has its custom modification and might keep updating the code. If we are using the Cosmos SDK official release. Is the submodule still necessary?

I think it's still necessary for the protobuf generation -- e.g. building the integration tests needs to build gRPC clients

**Review by yihuang — APPROVED** [review]

**Pull request merged**
