### PR TITLE
Problem: License file is not up-to-dated

### PR DESCRIPTION
**Pull request by calvinaco**
Solution: Update LICENSE file

### CODE REVIEW

**Review by tomtau — CHANGES_REQUESTED** [review]
the copyright is missing the copyright holder information, as per the Apache2 template: https://www.apache.org/licenses/LICENSE-2.0
```
Copyright [yyyy] [name of copyright owner]
```

**Comment by calvinaco** [comment]
> the copyrigh statementt is missing the copyright holder information, as per the Apache2 template (see "HOW TO APPLY THE APACHE LICENSE TO YOUR WORK"): https://www.apache.org/licenses/LICENSE-2.0
> 
> ```
> Copyright [yyyy] [name of copyright owner]
> ```

Updated, thanks!

**Review by tomtau — APPROVED** [review]
there are also notices in the modified files in x/nft -- I guess they should be updated as well?

**Comment by calvinaco** [comment]
> there are also notices in the modified files in x/nft -- I guess they should be updated as well?

Updated, there are some differences in the year between the LICENSE and the modification notice, I think it's because of the date the LICENSE file and the NFT module is added? Should we align them?

**Comment by tomtau** [comment]
it's probably ok as it is

**Pull request merged**
