### PR TITLE
Problem: not using the latest SDK release

### PR DESCRIPTION
**Pull request by tomtau**
Solution: bumped the dependency to Cosmos SDK v0.42.3

### CODE REVIEW

**Comment by JayT106** [comment]
Not sure what's the versioning rule in crypto.com. 
Is it belong to the bug fix version? (this PR upgraded cosmos SDK from v0.42.1 -> v0.42.3)
ref: https://datasift.github.io/gitflow/Versioning.html

**Comment by tomtau** [comment]
> Not sure what's the versioning rule in crypto.com.
> Is it belong to the bug fix version? (this PR upgraded the cosmos SDK from v0.42.1 -> v0.42.3). If yes, is it better if we use v1.1.1?
> ref: https://datasift.github.io/gitflow/Versioning.html

afaik the fix in SDK 0.42.3 has a slight change in the bank tx validation logic, hence the bump on the minor number

**Comment by JayT106** [comment]
> > Not sure what's the versioning rule in crypto.com.
> > Is it belong to the bug fix version? (this PR upgraded the cosmos SDK from v0.42.1 -> v0.42.3). If yes, is it better if we use v1.1.1?
> > ref: https://datasift.github.io/gitflow/Versioning.html
> 
> afaik the fix in SDK 0.42.3 has a slight change in the bank tx validation logic, hence the bump on the minor number

> > Not sure what's the versioning rule in crypto.com.
> > Is it belong to the bug fix version? (this PR upgraded the cosmos SDK from v0.42.1 -> v0.42.3). If yes, is it better if we use v1.1.1?
> > ref: https://datasift.github.io/gitflow/Versioning.html
> 
> afaik the fix in SDK 0.42.3 has a slight change in the bank tx validation logic, hence the bump on the minor number

Yes, I was thinking the SDK upgrade doesn't bring new features.

**Review by devashishdxt — APPROVED** [review]

**Review by devashishdxt — COMMENTED** [review]
I think it'll be better if we use `v1.1.1`. Since there are no major changes. As far as I understand, changing validation logic does not change the "application surface". If there are no breaking changes in the new version of cosmos-sdk (they've also increased the minor version), then `v1.1.1` is more appropriate for us.

**Review by linfeng-crypto — APPROVED** [review]

**Review by leejw51crypto — APPROVED** [review]
lgtm

**Pull request merged**
