### PR TITLE
Problem: missing upgrade to golang 1.16 (fix #416)

### LINKED ISSUE #416: Problem: missing upgrade to golang 1.16
Solution: upgrade to golang 1.16

### PR DESCRIPTION
**Pull request by leejw51crypto**
Solution: upgrade to golang 1.16 , which supports apple m1 officially

### CODE REVIEW

**Comment by yihuang** [comment]
Can you also update nixpkgs, recent version also have go1.16.
```
$ niv update nixpkgs -b nixpkgs-unstable
```

**Comment by leejw51crypto** [comment]
ok, i'll check

**Review by allthatjazzleo — APPROVED** [review]
LGTM

**Comment by tomtau** [comment]
integration test failing: https://github.com/crypto-org-chain/chain-main/pull/417/checks?check_run_id=2092726763#step:5:247

**Comment by yihuang** [comment]
> integration test failing: https://github.com/crypto-org-chain/chain-main/pull/417/checks?check_run_id=2092726763#step:5:247

probably also need to
```
$ niv update poetry2nix
```

**Comment by yihuang** [comment]
I opened separated nixpkgs upgrade in https://github.com/crypto-org-chain/chain-main/pull/418

**Review by yihuang — APPROVED** [review]

**Review by tomtau — APPROVED** [review]

**Pull request merged**
