### PR TITLE
Problem: changelog is not up to date for the release

### PR DESCRIPTION
**Pull request by tomtau**
Solution:
- updated the changelog
- bumped tendermint to the latest version
- bumped go version in CI actions

### CODE REVIEW

**Review by devashishdxt — APPROVED** [review]

**Review by YoutacRSVARs — APPROVED** [review]

**Review by YoutacRSVARs — APPROVED** [review]

**Review by JayT106 — APPROVED** [review]

**Review by yihuang — APPROVED** [review]

**Review by matias904 — COMMENTED** [review]
af09f85c769c3db76cda7f67c576d0cbfef3842c

**Review by matias904 — COMMENTED** [review]
af09f85c769c3db76cda7f67c576d0cbfef3842c

**Pull request merged**
