### PR TITLE
Problem: missing extended IBC integration tests (fix #504)

### LINKED ISSUE #504: Problem: missing extended IBC integration tests
- error cases with relayer failures
- 3 chain transfer (A,B)->C 1. A->C, 2. C->B

mentioned by @leejw51crypto

### PR DESCRIPTION
**Pull request by leejw51crypto**
Solution: add integration test (fix  #504)

### CODE REVIEW

**Comment by tomtau** [comment]
a few small linter issues in tests: https://github.com/crypto-org-chain/chain-main/pull/571/checks?check_run_id=2716991594#step:5:16

**Comment by leejw51crypto** [comment]
ok, i'll fix

**Review by tomtau — APPROVED** [review]
looks all right -- @leejw51crypto when I read the issue, I interpreted "a,b,c" as "chain a, chain b, chain c", but actually it is "account a on chain 0, account b on chain 0, account c on chain 1"... so perhaps good to write this down in the test comment for clarity?

**Comment by leejw51crypto** [comment]
yes, i'll write down the comments

**Pull request merged**
